apiVersion: v1
kind: Pod
metadata:
  name: grid-sync
  labels:
    tier: api
spec:
  volumes:
    - name: argovis-bulk
      persistentVolumeClaim:
        claimName: argovis-bulk
  containers:
  - name: schema
    imagePullPolicy: Always
    image: argovis/grid-sync:dev
    #command: ['sleep', '1000000']
    command: ['bash', 'rg-update.sh']
    volumeMounts:
      - mountPath: "/tmp"
        name: argovis-bulk
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 4000Mi
        cpu: 1000m
  restartPolicy: Never
