apiVersion: v1
kind: Pod
metadata:
  name: grid-sync
  labels:
    tier: api
spec:
  volumes:
    - name: ccmp
      persistentVolumeClaim:
        claimName: ccmp
  containers:
  - name: schema
    imagePullPolicy: Always
    image: argovis/grid-sync:dev
    command: ['sleep', '1000000']
    #command: ['bash', 'rg-update.sh']
    volumeMounts:
      - mountPath: "/tmp"
        name: ccmp
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 1000Mi
        cpu: 500m
  restartPolicy: Never
